FROM node:alpine as builder
WORKDIR /app
ADD railsapp/Gemfile Gemfile
ADD railsapp/Gemfile.lock Gemfile.lock
RUN bundle install
COPY package.json /app
RUN npm install
COPY . /app

RUN npm run build

FROM nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
