FROM node:alpine as builder
WORKDIR /app
COPY package.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build


FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html

COPY --from=builder /nginx.conf /etc/nginx/conf.d/default.conf
